# Generated by Django 4.1.4 on 2022-12-11 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_username', models.CharField(max_length=30, verbose_name="Bot's name")),
                ('bot_token', models.CharField(max_length=50, verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=30, verbose_name="Bot's name")),
                ('type', models.CharField(max_length=10, verbose_name='Type')),
                ('command', models.TextField(max_length=10, verbose_name='Command')),
                ('answer', models.CharField(max_length=255, verbose_name='Answer')),
                ('creating_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Date of changing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Command',
                'verbose_name_plural': 'Commands',
                'ordering': ['creating_date'],
            },
        ),
    ]
