# Generated by Django 4.0.6 on 2022-12-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_token',
            field=models.CharField(max_length=50, verbose_name="Bot's token"),
        ),
        migrations.AlterField(
            model_name='bot',
            name='bot_username',
            field=models.CharField(max_length=30, verbose_name="Bot's username"),
        ),
    ]
