# Generated by Django 4.1.1 on 2022-12-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='type',
            field=models.CharField(max_length=10, verbose_name='Type'),
        ),
    ]
