# Generated by Django 4.0.6 on 2022-12-11 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('constructor', '0002_alter_bot_bot_token_alter_bot_bot_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='user',
        ),
        migrations.AddField(
            model_name='bot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
