# Generated by Django 4.0.6 on 2022-12-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_remove_command_user_bot_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='command',
        ),
        migrations.AddField(
            model_name='command',
            name='bot_token',
            field=models.CharField(default=None, max_length=30, verbose_name='Token'),
        ),
        migrations.AddField(
            model_name='command',
            name='message',
            field=models.TextField(default='Target message', max_length=10, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='command',
            name='bot_name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='command',
            name='type',
            field=models.CharField(default='command', max_length=10, verbose_name='Type'),
        ),
    ]
