# Generated by Django 4.0.6 on 2022-12-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_remove_command_command_command_bot_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='answer',
            field=models.TextField(max_length=255, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='command',
            name='message',
            field=models.CharField(default='Target message', max_length=10, verbose_name=''),
        ),
    ]
