# Generated by Django 4.0.6 on 2022-12-12 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_alter_command_type'),
        ('constructor', '0005_alter_command_answer_alter_command_message'),
    ]

    operations = [
    ]
