# Generated by Django 4.0.6 on 2022-12-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0006_merge_20221212_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='type',
            field=models.CharField(default='command', max_length=10, verbose_name='Type'),
        ),
    ]
