# Generated by Django 4.0.6 on 2022-12-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0008_bot_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='script',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/scripts/file.txt', upload_to='files/', verbose_name='Script'),
        ),
    ]
