# Generated by Django 4.0.6 on 2022-12-13 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0010_alter_bot_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='script',
        ),
    ]
