# Generated by Django 4.0.6 on 2022-12-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0011_remove_bot_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='has_script',
            field=models.BooleanField(default=False, verbose_name='Has script?'),
        ),
    ]
