# Generated by Django 4.0.6 on 2022-12-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0012_bot_has_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='script_path',
            field=models.CharField(default='', max_length=70, verbose_name='path'),
        ),
    ]
