# Generated by Django 4.1.1 on 2022-12-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='telegram',
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=40, verbose_name='Telegram id'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
